name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - main

env:
  ECR_REPO: 924144197303.dkr.ecr.us-east-1.amazonaws.com/test
  AWS_REGION: us-east-1
  IMAGE_VERSION: ${{ github.ref_name }}  # Branch name used as a version

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Clear AWS Credentials Cache
        run: rm -rf ~/.aws

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_REGION }}

      - name: Get Git Commit SHA and Tag
        id: git_commit
        run: |
          git fetch --tags
          COMMIT_SHA=$(git rev-parse HEAD)
          TAG_NAME=$(git describe --tags --abbrev=0 || echo "latest")

          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.ECR_REPO }}:${{ env.COMMIT_SHA }}
            ${{ env.ECR_REPO }}:${{ env.IMAGE_VERSION }}
            ${{ env.ECR_REPO }}:${{ env.TAG_NAME }}
